### PR TITLE
Add patches for 6.9

### PR DESCRIPTION
**Pull request by leonm1**
Patches derived from applying 6.8 patches atop github.com/grekh/linux v6.9.3 (1b4861e32e46) and fixing the conflicts.

Notable conflicts

* 0004-ipts.patch
  * Some changes to drivers/iommu/intel/iommu.c caused merge conflicts because adjacent workarounds were removed in ba00196ca41c. It does not appear to matter.
* 0012-cameras.patch
  * "media: ipu3-cio2: Further clean up async subdev link creation" seems to have been upstreamed as commit b97dc22b195f

### CODE REVIEW

**Comment by LionHeartP** [comment]
Hello.
I'm currently building a 6.9.3 kernel for Nobara Linux.
I'm using this patchset which applies *almost* cleanly as you can see here https://github.com/LionHeartP/rpm-sources/blob/kernel/baseos/kernel/6.9.3/linux-surface.patch

The only problem I have is that on patch https://github.com/leonm1/linux-surface/blob/6.9/patches/6.9/0009-surface-typecover.patch there's a conflict between the patchset from T2Linux folks so I'm rebasing a hunk of that with this https://github.com/LionHeartP/rpm-sources/blob/kernel/baseos/kernel/6.9.3/t2-surface-hid-multitouch.patch

The problem I have with the end result, is that we tested on a Surface 6 (with i5) and it has the following issues.

Keyboard and multitouch is not working. Keyboard appears to be connected (it makes the sound and also lights up) but there's no functionality.

About the multitouch issue, I'm sure my trying to merge both your changes to hid-multitouch.c and the ones from the t2linux git is somehow making it non functional, but not sure about the keyboard issue.

Please let me know if there's more info I can provide.

**Comment by qzed** [comment]
I'll have a look at this on the weekend.

On the Pro 6, the keyboard should be a standard USB keyboard and we don't have any changes that are required to make it work. IIRC the only things touching hid-multitouch.c are for the typecover keyboard backlight and adding a tablet-mode switch. So you could try to drop the changes in surface-typecover.patch entirely and see if that helps.

**Comment by StollD** [comment]
Something that also needs to be considered for 6.9: The option that we have been using to get our kernels to boot on Fedora with the newer firmware doesn't exist anymore, so it has to be replaced by a patch.

 * https://github.com/linux-surface/linux-surface/blob/master/pkg/fedora/kernel-surface/configs/fedora.config#L14
 * https://github.com/torvalds/linux/commit/891f8890a4a3663da7056542757022870b499bc1

**Comment by qzed** [comment]
Merged. I've updated the patches for 6.9.3 and also merged the SL6 SAM support.

**Pull request merged**
