### PR TITLE
Draft: add support for Fedora 39

### LINKED ISSUE #1254: Package for Fedora 39
Fedora Workstation 39 beta is out, so this could be a good opportunity to package and test linux-surface on the latest release of Fedora.

I took a look at commit 5bdb795 and at the files `.github/workflows/fedora-37.yml` and `.github/workflows/fedora-38.yml`. It seems that making a new package would only require creating a new file `.github/workflows/fedora-39.yml`, replacing all occurrences of "`38`" with "`39`".

I can submit a PR with these changes and test the package in Fedora Silverblue 39 machine (Surface Book 1).

### PR DESCRIPTION
**Pull request by pesader**
I added a GitHub Actions workflow file to package for Fedora 39. However, I'm not sure how I can build and install them locally to test it and consider it ready.

I saw that @StollD did some work on the Fedora packaging, so any feedback here would be greatly appreciated :)

Thanks for developing linux-surface and making my computer work!

Closes #1254

### CODE REVIEW

**Comment by StollD** [comment]
> I added a GitHub Actions workflow file to package for Fedora 39. However, I'm not sure how I can build and install them locally to test it and consider it ready.

Run these commands to install the dependencies: https://github.com/linux-surface/linux-surface/blob/master/.github/scripts/package/fedora.sh#L21-L28

Then go into `pkg/fedora/kernel-surface` and run `python3 build-linux-surface.py`.

We are currently still on kernel 6.4, so I don't know how well that will build on F39. But I doubt it's going to cause any issues. I see that @qzed already rebased the patches, so I will look into updating our packages soon-ish (got an exam in a few days).

**Comment by qzed** [comment]
I'll try to update patches/kernel packages today.

**Comment by qzed** [comment]
So I've updated 6.1 and 6.4 patches, but haven't created 6.5 ones yet (and also not pushed any new kernel packages). For that, I think we should wait until we have fixed the suspend issue. It looks like that likely affects a bunch of devices, so it's quite a deal-breaker now.

**Comment by pesader** [comment]
> So I've updated 6.1 and 6.4 patches, but haven't created 6.5 ones yet (and also not pushed any new kernel packages).

Good stuff!

> For that, I think we should wait until we have fixed the suspend issue. It looks like that likely affects a bunch of devices, so it's quite a deal-breaker now.

I can help with testing if Surface Laptop 1 is affected.

**Comment by GloriousEggroll** [comment]
> So I've updated 6.1 and 6.4 patches, but haven't created 6.5 ones yet (and also not pushed any new kernel packages). For that, I think we should wait until we have fixed the suspend issue. It looks like that likely affects a bunch of devices, so it's quite a deal-breaker now.

Can confirm it causes Steam Deck hibernate (Sleep) to break. I've been trying to figure this out for a few days and this issue was brought to my attention. Disabling the entire patchset fixes the Steam Deck. I'll see if I can bisect down which patch is causing it (unless you already know which one, which would help)

**Comment by GloriousEggroll** [comment]
> @GloriousEggroll Wait, our surface patches are causing the suspend on the Steam Deck to break?
> 
> The issue I was talking about should be exclusive to Surface devices. In short: We have a EC that we need to communicate with when preparing for suspend, but we don't receive responses from it. We do receive the responses only when we resume. But as I've said, the EC and driver for that are Surface specific, so that shouldn't cause any issues on the Steam Deck. Maybe there's some other issue that we're not even hitting yet because of the EC one?

Yes, I confirmed this morning disabling the patchset allows Steam Deck suspend to work again. Adding the patchset causes the Steam Deck to not wake from hibernate. I'm currently looking now to try to figure out which patch, starting with acpi related ones.

**Comment by GloriousEggroll** [comment]
fwiw I see these are specific to surface:

Subject: [PATCH] ACPI: Add quirk for Surface Laptop 4 AMD missing irq 7
 override
 
 Subject: [PATCH] ACPI: Add AMD 13" Surface Laptop 4 model to irq 7 override
 quirk
 
 But this one does not and might be sus:
 Subject: [PATCH] acpi: allow usage of acpi_tad on HW-reduced platforms

The specification [1] allows so-called HW-reduced platforms,
which do not implement everything, especially the wakeup related stuff.

In that case, it is still usable as a RTC. This is helpful for [2]
and [3], which is about a device with no other working RTC,
but it does have an HW-reduced TAD, which can be used as a RTC instead.

[1]: https://uefi.org/specs/ACPI/6.5/09_ACPI_Defined_Devices_and_Device_Specific_Objects.html#time-and-alarm-device
[2]: https://bugzilla.kernel.org/show_bug.cgi?id=212313
[3]: https://github.com/linux-surface/linux-surface/issues/415

**Comment by qzed** [comment]
Yeah, I guess that might affect other devices. Maybe we should put a DMI-match guard on that or just use the Surface EC for the RTC driver. Also, the camera patches are not exclusive to Surface devices, if you pull those in.

**Comment by GloriousEggroll** [comment]
nevermind for now. for some reason my build is now failing to wake even without the patchset. ignore my comments for now. ill update again if i find something related to the patchset.

**Comment by qzed** [comment]
For our EC problem I've added #1258.

**Comment by qzed** [comment]
I've found a workaround and set up some new releases with that. It's not a particularly great workaround, but for the time being it should be enough. Will finally get us some v6.5 kernels at least. I'll look into F39 support tomorrow.

**Comment by Streammet** [comment]
Im still stuck on Fedora 38 with the 6.4 Kernel. Is that normal? I cant upgrade no matter what.

**Comment by qzed** [comment]
I've been able to update to Fedora 40 on my SB2 without any issues.

**Pull request merged**
