### PR TITLE
arch: pkg-kernel: update to 5.7.2-arch1

### PR DESCRIPTION
**Pull request by kitakar5525**
I updated Arch kernel PKGBUILD and config.

Based PKGBUILD tree:
- https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux&id=8f2bbde26d3b242217233a4b3f0a6c8171ffc492 ("5.7.2.arch1-1")

There are a few things to note:
- arch enabled `CONFIG_DEBUG_INFO=y` via commit ["5.7.1.arch1-1"](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=663b08666b269eeeeaafbafaee07fd03389ac8d7)
  So, we may want to consider disabling it like we did for the other distros? That said, in PKGBUILD, it strips debug info [here](https://github.com/linux-surface/linux-surface/pull/210/commits/3d444b79e8b199d3a70e449a599abc3ad87f0685#diff-5e71f78fcff8cc0e0a50b24339132b9fR114) and [here](https://github.com/linux-surface/linux-surface/pull/210/commits/3d444b79e8b199d3a70e449a599abc3ad87f0685#diff-5e71f78fcff8cc0e0a50b24339132b9fR191). So, the size of the generated package did not increase but the disk space required for the build may increase.

- `pahole` is required as build dependency if we keep `CONFIG_DEBUG_INFO_BTF=y`:
```bash
BTF: .tmp_vmlinux.btf: pahole (pahole) is not available
Failed to generate BTF for vmlinux
Try to disable CONFIG_DEBUG_INFO_BTF
make: *** [Makefile:1113: vmlinux] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```
  but the package is not needed if we disable `CONFIG_DEBUG_INFO`

---

By the way, if you use refind and can't boot 5.7 kernels, take a look at archwiki:
> Use backslashes (\\) as path separators in all quoted initrd parameters, otherwise the kernel may fail to find the initramfs image(s):
> EFI stub: ERROR: Failed to open file: /boot/initramfs-linux.img.
> 
> https://wiki.archlinux.org/index.php/REFInd#Manual_boot_stanzas

So, I had to replace lines like this:
```diff
- initrd=/boot/intel-ucode.img initrd=/boot/initramfs-
+ initrd=\boot\intel-ucode.img initrd=\boot\initramfs-
```

### CODE REVIEW

**Comment by kitakar5525** [comment]
I forgot to update pkg/arch/kernel/surface.config (link to `../../../configs/surface-5.7.config`) (https://github.com/linux-surface/linux-surface/pull/210/files#diff-5c3303754f4ff2a0c11b08d1074790e5R1). Updated.

**Comment by qzed** [comment]
Thanks, I'm going to build and test this shortly.

> * arch enabled `CONFIG_DEBUG_INFO=y` via commit ["5.7.1.arch1-1"](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=663b08666b269eeeeaafbafaee07fd03389ac8d7)
>       So, we may want to consider disabling it like we did for the other distros?

IIRC the reason we disabled debug info everywhere were memory requirements. It's probably best if we add a something like a build.config to override that (i.e. merge that in [here](https://github.com/linux-surface/linux-surface/blob/13854fcc45889e67ab7dc27ba7fca259181903fe/pkg/arch/kernel-lts/PKGBUILD#L88)), that way we don't have to edit the original Arch config.

**Comment by kitakar5525** [comment]
I pushed update:
- disable `CONFIG_DEBUG_INFO`
- remove `pahole` from deps

**Comment by qzed** [comment]
Tested. So far no new glaring issues.

**Pull request merged**
