### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by archseer**
Remaining items:

- [x] Figure out if [snd-hda-intel.conf](https://github.com/linux-surface/linux-surface/blob/289f9d67e36573cd5fe79936850e8a24ff482195/root/etc/modprobe.d/snd-hda-intel.conf) is necessary. It looks like it's [targetting an older sound card](https://askubuntu.com/questions/706602/how-do-i-get-sound-with-an-hda-card#727855). It shouldn't be installed for all devices because audio works fine on Ice Lake without that file.

- [x] ~~Rephrase the localtime option? Arch seems to hint that it's better to fix this in Windows ("To dual boot with Windows it is recommended to configure Windows to use UTC, rather than Linux to use localtime.")~~

### CODE REVIEW

**Comment by PandorasFox** [comment]
I'd say it's definitely not better to "fix" it via registry in Windows - it's far easier to handle it in Linux and it feels a lot less hacky? (plus personally I reinstall Windows way more than I ever reinstall Linux)

**Comment by archseer** [comment]
The Ubuntu guide says "The advantage of having the hardware clock as UTC is that you don't need to change the hardware clock when moving between timezones or when Daylight Savings Time (DST) begins or ends as UTC does not have DST or timezone offsets.",  but then "Changing Linux to use local time is easier and more reliable than changing Windows to use UTC, so dual-boot Linux/Windows systems tend to use local time."

I guess we can keep the current default because it's less friction to get it working

**Comment by danielzfranklin** [comment]
I'd recommend phrasing it more decisively. Something like "Change Linux to use localtime for Windows compatibility. Enter no if you aren't dual-booting."

**Comment by archseer** [comment]
Looks like the `snd-hda-intel.conf` addresses a Surface Book 2 issue. https://github.com/jakeday/linux-surface/issues/426

Would be good if someone tested without the file to see if the problem is still present. Otherwise it should somehow be made a conditional install, since the new models definitely don't need this change.

**Comment by danielzfranklin** [comment]
I have a Surface Book 2 and would be happy to test @archseer.

I don't see that file referenced in setup.sh; is it a part of the kernel and would I have to build the kernel? I can't find anything about building from source in the README, if that's necessary I'd appreciate a pointer.

Also, is the test to see if I can hear a sound played with the built-in speakers after booting?

**Comment by archseer** [comment]
It's just [this config file](https://github.com/linux-surface/linux-surface/blob/0d3e0c975abd7a9283e07a00d40e529373261bf0/root/etc/modprobe.d/snd-hda-intel.conf) that's copied to `/etc/modprobe.d/snd-hda-intel.conf`.

Try removing the file and check if any of these errors re-appear:
> Before applying this fix there are 3 problems:
>
> - only left speaker works.
> - volume adjust has no effect.
> - sound still comes out through speaker when headphone is plugged-in.

**Comment by qzed** [comment]
> I guess we can keep the current default because it's less friction to get it working

While I personally prefer to have the device set to UTC (as that makes more sense to me personally), changing that in Windows requires editing stuff in the registry and I don't think we want to burden the average user with that. I agree that setting localtime in Linux is easier for everyone involved, and I don't see any downsides of that.

> Looks like the `snd-hda-intel.conf` addresses a Surface Book 2 issue. [jakeday#426](https://github.com/jakeday/linux-surface/issues/426)
> 
> Would be good if someone tested without the file to see if the problem is still present.

I've been running on the SB2 without pretty much any of the config files since for a long time now. I had the sleep script up until the wifi patch change, and I've added the `wifi.powersave = 2` after that to the NetworkManager config. Apart from that I've blacklisted the nouveau drivers but I'm not sure if that is necessary any more.

The only issue with sound that I have is when connecting to the Surface Dock, the sound output doesn't change from speakers to the dock, but I think that's an application issue (restarting e.g. spotify fixes that). And I'm pretty sure I've also had the same issue on other devices...

**Comment by archseer** [comment]
Alright, I'll go ahead and drop the `snd-hda-intel.conf` file then if no objections?

**Pull request merged**
