### PR TITLE
doc: add IRC channel

### PR DESCRIPTION
**Pull request by Tyler-2**
The IRC support channel wasn't published here.

### CODE REVIEW

**Comment by Tyler-2** [comment]
Someone would need to bridge the Matrix support channel to the IRC support channel - I just assumed that had been done.

**Comment by StollD** [comment]
The support channel is matrix-only and not linked to IRC.

**Comment by Tyler-2** [comment]
Being unfamiliar with Matrix - why not? Is there a cost or significant management overhead involved in bridging?

**Comment by StollD** [comment]
If a Matrix channel is bridged to IRC you need to stop treating it as a Matrix channel and instead treat it as an IRC channel that you joined with a Matrix client. The bridge does not properly map all features of Matrix to IRC, this results in messages getting reposted when you edit them, messages that are too long get sent as a pastebin link etc. etc.

Since the support channel is mainly directed at end users, who have come to expect these features from Discord, Slack, and so on, we decided to not bother with bridging so we dont have an IRC channel where every conversation gets annoying for its users.

**Comment by Tyler-2** [comment]
Wellllll that sucks. Thanks.

**Pull request closed without merging**
