### PR TITLE
Update Fedora kernels to v6.11.6

### LINKED ISSUE #1594: [SP7] Bluetooth not working
### Description

I did a clean installation of Fedora40 yesterday and everything appears to work as expected.
The only thing that refuses to work appears to be bluetooth.

Theres nothing suspicious in the dmesg or journal besides every attempt being refused.
`Failed to set mode: Busy (0x0a)`

### Environment
- Hardware model: Surface Pro 7
- Kernel version: `6.11.4-1.surface.fc40.x86_64`
- Distribution: `Fedora Linux 40 (Workstation Edition)`

#### dmesg output

[Link due to Github 65536 character limit reached](https://paste.systemli.org/?a8739e7dc55b50c0#89upzHcrgrHR8JBSMBZ7ZWxFze2bwkXUkp8BW6zYf77M)
</details>

### PR DESCRIPTION
**Pull request by otjamin**
Update the Fedora kernel to the latest stable version.

I have tested the build and so far I have not noticed any problems.

This fixes #1594.

### CODE REVIEW

**Comment by otjamin** [comment]
Related to this: Do you think patch updates should be automated or could this cause problems with the Surface patches? @StollD 

So when there is a new patch version like 6.11.7 the pipeline will build (semi-)automatically. Best in sync with the official Fedora kernel version.

**Comment by vdbdwayne** [comment]
@otjamin do you have instructions on how to build and install the kernel with your change.  
I got as far as running build-linux-surface.py successfully (without the secureboot though I would like to be able to include this) but unsure where to go from there and the documentation looks to be debian focused

**Comment by otjamin** [comment]
> @otjamin do you have instructions on how to build and install the kernel with your change. I got as far as running build-linux-surface.py successfully (without the secureboot though I would like to be able to include this) but unsure where to go from there and the documentation looks to be debian focused

Hi @vdbdwayne, I am building with GitHub actions. You can get the latest Fedora kernel from my [last runs](https://github.com/otjamin/linux-surface/actions) artifacts.

Download the archive, unpack and remove the following rpms: kernel-surface-devel, kernel-surface-devel-matched, kernel-surface-modules-extra, kernel-surface-modules-internal

Finally, simply run `dnf in "kernel-surface*"` from the extracted folder.

I cannot provide a version that works with secureboot because I do not have the official keys.  If you want to build it yourself with secureboot support, you have to follow some instructions to create your own secureboot keys and build with them. (Imho it's not worth the effort for this temporary solution, unless you want to learn something new and have the time.)

**Comment by vdbdwayne** [comment]
Thank you very much @otjamin, found the artifacts for the install.

**Comment by qzed** [comment]
v6.11.11 builds are running for Fedora. Thanks for the PR!

**Comment by otjamin** [comment]
> Related to this: Do you think patch updates should be automated or could this cause problems with the Surface patches? @StollD 
> 
> 
> 
> So when there is a new patch version like 6.11.7 the pipeline will build (semi-)automatically. Best in sync with the official Fedora kernel version.
> 
> 
> 
> 

What do you think about this @qzed ?

**Comment by qzed** [comment]
I was actually toying with the idea in the past. It should be fairly easy to rebase and regenerate the patches for minor releases using the upstream tags. Possibly this could also work for major releases as long as there is no conflict. That's all on the kernel repo side though.

For the packages we would need something that checks the latest package versions and acts based on that. Ideally something that then also checks if the rebase on the kernel repo was successful (and if necessary waits on that). That part would probably be a quite a bit more complex than I'd like.

**Comment by otjamin** [comment]
I'll look into it when I find the time. But I need to learn a bit more about kernel patching and the whole process first.

But when I get around to it, I'll open a draft PR to track the progress.

**Pull request closed without merging**
