### PR TITLE
Automated kernel builds

### LINKED ISSUE #28: Save choices for setup.sh
# Feature Request: Save choices for setup.sh

## Problem
I have to carefully read through every question when I want to upgrade even though I want the same things as last time for all the questions that haven't changed.

## Proposed solution
I propose that `setup.sh` saves the response to everything it `ask`s to a standard location. On future runs by default any question with a saved response isn't asked again.

If a question requires new thought, the phrasing should change. As responses are indexed under question phrasing the question will be asked anew. (This should be the case anyhow because people skimming through the questions should be alerted if they require new thought.)

Outdated responses are left in the config file for simplicity. Users shouldn't need to edit the config file directly, so a few bytes of clutter won't matter. If setup.sh drastically changes the config file can be deleted.

The config file can be deleted by running `setup.sh --fresh-start`. (Poorly named I think, suggestions?).

### Technicalities
- If config file doesn't yet exist standard location is `$XDG_CONFIG_HOME/.linux_surface/config` if `$XDG_CONFIG_HOME` is defined, `~/.config/linux_surface/config` if directory `~/.config` exists, else `~/.linux_surface.conf`. Order of priorities is reversed for existing files so that if a user has `~/.linux_surface.conf` already that would be used even if they have a config directory.
- Config format is INI so that it can [be parsed](https://github.com/albfan/bash-ini-parser) with pure bash
- Answers are indexed under their URL slug form as that [can be done](https://stackoverflow.com/a/49035906/8334056) with bash and coreutils

### LINKED ISSUE #32: Rethinking parts of installation
Some ideas I had while tweaking the install guide.

https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup

Things I want to do:
- stop having setup.sh install kernel & wacom packages
- possibly have a ./download.sh <optional: arch/debian/fedora> that would download packages for you and echo the command needed to run
  - ok, if we do that, maybe have the setup script call that script?
- package the firmware we have as a package, similar to linux-firmware (instead of copying files into /lib directly)
- stop shipping the kernel with surface_sam and offer it as a dkms package, that way it's easier to upgrade separately (or for users to test, we don't need to compile a full kernel for them), and in another iteration or two it'll work
- add a pkg/ folder containing pkg/arch, pkg/fedora etc. for the kernel + acpi module. Those will contain up-to-date PKGBUILDS/build scripts that the user can use instead of pre-built packages.

The rationale is that with the upcoming simpler setup.sh (#22), the only distro-specific aspect is just installing/building the packages. This would make the installation guide a lot simpler, because it would have a lot less notices and conditionals (right now it's "if debian do this, but if arch, either use this other package you need to download manually or look at this third-party repo, or something else entirely, and say no in `setup.sh` 😅")

It would look something like:

[...] follow the guide to setup linux
1. run `./setup.sh`
2. obtain kernel & other packages
  a) run ./download.sh <distro> to fetch your packages 
  b) _or_ use the package repository
  c) _or_ build them yourself (use pkg/<distro>)
3. install all the things! (`pacman -U *.tar.zstd`)
4. update bootloader
5. reboot
6. post install
6.1 do general post install steps
6.2 do device specific post install steps by looking at the device's wiki page that addresses various quirks

### LINKED ISSUE #45: Package linux-libc-dev-5.3.18-surface unavailable in Debian Repository
Currently following the guide to get Ubuntu 18.04 working on my brand new SB2.

On item 4 (Download and install the required packages), it mentions 3 kernel packages to install, one of them being: linux-libc-dev-[VERSION].deb

I installed the debian repository as per [https://github.com/linux-surface/linux-surface/wiki/Package-Repositories](url). Trying to install 5.3.18 as I want touch support.

However, no package matches linux-libc-dev_5.3.18* . an apt-cache search 5.3.18 only yields:
- linux-headers-5.3.18-surface
- linux-image-5.3.18-surface

Could you help me understand:
1. why the -dev package is not there. Should it be?
2. Do I need to install it? I can manually download it and install via dpkg, but that defeats the purpose of installing everything via the repository.

Thanks for the help!

### LINKED ISSUE #98: 404 on https://tmsp.io/fs/tmsp.asc (key used to sign Debian packages)
404 on https://tmsp.io/fs/tmsp.asc (key used to sign Debian packages)
https://github.com/linux-surface/linux-surface/wiki/Package-Repositories

### LINKED ISSUE #100: Invalid Signature after enrolling MOK
After enrolling the MOK.cer from MokManager, and then re-enabling Secure Boot (Microsoft & 3rd party CA), I get the following error after passing the Surface logo during boot:

```
error: /boot/vmlinuz-5.5.4-surface has invalid signature
error: you need to load the kernel first
```

### Environment
- Hardware model: SL3 Intel
- Distribution: kubuntu 19.10

</details>

### PR DESCRIPTION
**Pull request by archseer**
Opening a draft so we can track what's left to ship this.

- [x] Update the IPTS patch to latest revision with the gen7 bugfix
- [x] Update arch kernel-lts to 5.4 lts
- [x] Update arch to 5.5
- [x] Update fedora to 5.5
- [x] Update debian to 5.5

Note: We need to ship/switch the secureboot-mok package at the same time as the new kernel packages, due to the MOK change. This should also be made aware to all users updating to those releases, as it will break secure-boot if the new MOK hasn't been installed.

#### Package repository

- [x] Change update procedure to ensure that multiple concurrent repo updates don't crash due to merge conflicts
- [x] Push to releases before pushing to repo (otherwise files will not be available if something goes wrong after a repo has been updated)
- [x] Re-point the surfacelinux domain
- [ ] ???

Fixes #98 
Fixes #100
Fixes #28
Fixes #32
Fixes #45

### CODE REVIEW

**Comment by qzed** [comment]
Couple of comments:
- 2b4f321 should work, so all that's left is Fedora.
- I don't think updating Arch-LTS to 5.4 (eabeaf1) is a good idea: 5.4 doesn't support legacy IPTS and until we've got that fixed we should at least provide one release with full IPTS support. 4.19 still isn't EOL, so we should keep it, even if that means diverging from Arch.
- We should probably think about splitting this up into two parts: 1) Automated kernel builds and 2) automated repo updates. Maybe that way we can get the builds published a bit earlier, although without the repo.

**Comment by archseer** [comment]
I'll revert the Arch LTS change.

Yeah I'm planning to split off the list of items related to the repository into a new issue. I think we should focus entirely on getting automated releases before we do any of the repo stuff.

**Comment by qzed** [comment]
I think pretty much all that's needed for that part is updating Fedora to 5.5. Adding the IPTS gen7 stuff shouldn't be a problem, just push the changes to the devel branches.

At the moment I'm focusing on the repo stuff as I feel that's where I can be most productive. I don't really have much of a clue regarding the fedora kernel builds.

**Comment by archseer** [comment]
I think I can have the fedora package updated later today, but can you update the IPTS patch if you have time?

**Comment by qzed** [comment]
> can you update the IPTS patch if you have time?

Done, updated patches are in master.

**Comment by archseer** [comment]
@qzed We can probably ship Fedora with 5.4, 5.5 isn't available yet.

**Comment by archseer** [comment]
Also we'll need to update the Arch PKGBUILD again to use the updated IPTS patch & sha256.

**Comment by qzed** [comment]
Yeah, I think we should just update Fedora later on. I think we should also run test builds for everything before we merge, to get all the minor issues fixed like updating pkgsums as you mentioned.

**Comment by qzed** [comment]
Btw. regarding the repo-automation: both Arch and Debian should be ready, just finished up on Debian. I've also got something for Fedora, but that still needs to be tested.

**Comment by qzed** [comment]
The repo automation should now be feature complete. All non-kernel packages are updated and in the repo, pushing the kernel packages should also work.

**Comment by StollD** [comment]
Fedora 31 has been rebased to 5.5, I think 30 should follow soon. In the meantime I updated it to the latest 5.4 stable release

**Comment by archseer** [comment]
I think what's left is for the releases section to be cleaned up, `-test` removed from all the builds, then a rebuild and the repo server configured. Then we're ready to 🚢

**Comment by archseer** [comment]
With `pkg/keys/` now existing, should we get rid of the `keys/` folder on this branch?

**Comment by qzed** [comment]
Yeah, the keys in that directory are outdated and can be removed.

**Comment by qzed** [comment]
Did that, removed the old workflow file and removed the testing packages from the repo. I think we should set up configs for the specific versions before we merge. Anything else that needs clean-up?

**Comment by qzed** [comment]
>  I think we should set up configs for the specific versions before we merge.

Done.

**Comment by StollD** [comment]
Fedora 30 has been rebased to 5.5 as well.

**Comment by archseer** [comment]
🎊

**Pull request merged**
